In [1]:
import os
import pandas as pd
from pathlib import Path

In [2]:
base_dir = "./Uilenstede"
for filename in os.listdir(base_dir):
    print(filename)

Accelerometer.csv
AccelerometerUncalibrated.csv
Activity.csv
Annotation.csv
Barometer.csv
Compass.csv
Gravity.csv
Gyroscope.csv
GyroscopeUncalibrated.csv
Location.csv
Magnetometer.csv
MagnetometerUncalibrated.csv
Metadata.csv
Network.csv
Orientation.csv
Pedometer.csv
TotalAcceleration.csv
WatchAccelerometer.csv
WatchBarometer.csv
WatchGravity.csv
WatchGyroscope.csv
WatchLocation.csv
WatchMagnetometer.csv
WatchOrientation.csv
WatchTotalAcceleration.csv
WiFi.csv

In [3]:
folder = Path("./Uilenstede")

for csv_file in folder.glob("*.csv"):
    print(f"=== {csv_file.name} ===")
    try:
        df = pd.read_csv(csv_file)
        if df.empty:
            print("File is empty.\n")
            continue

        display(df.head(3))
        print("\n")

    except pd.errors.EmptyDataError:
        print("File is empty or has no columns.\n")
    except Exception as e:
        print(f"Could not read {csv_file.name}: {e}\n")

=== Accelerometer.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789948640308700         0.104309  0.000000  0.000000  0.000000
1  1774789948677358300         0.141358  0.432748 -0.056351 -0.057238
2  1774789948695883300         0.159883  1.092300 -0.207151  0.070466

=== AccelerometerUncalibrated.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789948724751400         0.188751  8.803194  5.020142 -0.191426
1  1774789948743276000         0.207276  8.281559  4.776074 -0.531207
2  1774789948761801000         0.225801  8.465807  4.570291 -0.787239

=== Activity.csv ===

                  time  seconds_elapsed activity
0  1774789948818000000            0.282  unknown
1  1774789953917000000            5.381  walking
2  1774789967208000000           18.672  walking

=== Annotation.csv ===

                  time  seconds_elapsed     text  millisecond_press_duration
0  1774789952933000000            4.397  Walking                          62
1  1774789975639000000           27.103  Sitting                           2

=== Barometer.csv ===

                  time  seconds_elapsed  relativeAltitude     pressure
0  1774789948792434400         0.256434          0.000000  1023.359375
1  1774789948832438500         0.296438         -0.137398  1023.376465
2  1774789948872441300         0.336441         -0.142685  1023.376709

=== Compass.csv ===

                  time  seconds_elapsed  magneticBearing
0  1774789948667543600         0.131543       258.098922
1  1774789948677543700         0.141544       253.353411
2  1774789948697543700         0.161544       247.000030

=== Gravity.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789948640308700         0.104309  8.026459  5.628912 -0.248372
1  1774789948677358300         0.141358  8.079538  5.556170 -0.142901
2  1774789948695883300         0.159883  8.248864  5.303455 -0.001130

=== Gyroscope.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789948649571000         0.113571 -0.443030 -1.452636  0.322231
1  1774789948668096000         0.132096 -0.432645 -1.555262  0.084605
2  1774789948695883300         0.159883 -0.428980 -0.986547 -0.176234

=== GyroscopeUncalibrated.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789948714408000         0.178408 -0.459370 -0.687834 -0.292604
1  1774789948732932900         0.196933 -0.503963 -0.474031 -0.356745
2  1774789948751457500         0.215458 -0.490524 -0.461814 -0.437990

=== Location.csv ===

,time,seconds_elapsed,bearingAccuracy,speedAccuracy,verticalAccuracy,horizontalAccuracy,speed,bearing,altitude,longitude,latitude
0,1774789955023206100,6.487206,0.0,1.5,2.033221,26.521000,0.058193,0.0,67.199997,4.874664,52.319263
1,1774789955625767700,7.089768,0.0,1.5,2.033221,26.607000,0.057189,0.0,67.199997,4.874664,52.319264
2,1774789956328812800,7.792813,0.0,1.5,2.041996,26.735001,0.053330,0.0,67.199997,4.874664,52.319264

=== Magnetometer.csv ===

                  time  seconds_elapsed          z        y          x
0  1774789948667543600         0.131543 -42.243752 -3.67500  17.437500
1  1774789948677543700         0.141544 -40.968750 -3.91875  13.106251
2  1774789948697543700         0.161544 -40.631252 -4.16250   9.806251

=== MagnetometerUncalibrated.csv ===

                  time  seconds_elapsed          z          y        x
0  1774789948697543700         0.161544 -46.687500  48.337502 -0.69375
1  1774789948717543700         0.181544 -54.037502  48.975002  4.42500
2  1774789948727543600         0.191543 -51.956253  50.006252 -0.50625

=== Metadata.csv ===

,version,device name,recording epoch time,recording time,recording timezone,platform,appVersion,device id,sensors,sampleRateMs,standardisation,platform version
0,3,SM-S911B,1774789948536,2026-03-29_13-12-28,Europe/Amsterdam,android,1.55.0,1c2b50a5-0d41-4269-89cd-d6a734f19c03,Accelerometer|Gravity|Gyroscope|Orientation|Ma...,10|10|10|10|10|10|0|0|10|10|10|10|0|2000|40000...,True,36

=== Network.csv ===

,time,seconds_elapsed,type,isConnected,isInternetReachable,isWifiEnabled,isConnectionExpensive,ssid,bssid,strength,ipAddress,frequency,cellularGeneration,carrier
0,1774789950547000000,2.011,wifi,True,True,True,False,MEA,d8:47:32:c7:ec:8e,37,192.168.0.110,2412,NaN,NaN
1,1774789952547000000,4.011,wifi,True,True,True,False,MEA,d8:47:32:c7:ec:8e,37,192.168.0.110,2412,NaN,NaN
2,1774789954547000000,6.011,wifi,True,True,True,False,MEA,d8:47:32:c7:ec:8e,37,192.168.0.110,2412,NaN,NaN

=== Orientation.csv ===

,time,seconds_elapsed,qz,qy,qx,qw,roll,pitch,yaw
0,1774789948668096000,0.132096,0.298179,0.104876,0.282123,0.905813,0.026555,-0.610948,-0.627649
1,1774789948695883300,0.159883,0.269332,0.079169,0.270476,0.920888,0.000137,-0.571390,-0.569028
2,1774789948714408000,0.178408,0.264863,0.071825,0.263085,0.924919,-0.007634,-0.552377,-0.559963

=== Pedometer.csv ===

                  time  seconds_elapsed  steps
0  1774789945843022600        -2.692977      0
1  1774789957374372900         8.838373      6
2  1774789957967303700         9.431304      7

=== TotalAcceleration.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789948687701800         0.151702  8.932407  4.833502  0.069392
1  1774789948715489000         0.179489  8.894122  5.075177 -0.105284
2  1774789948734013700         0.198014  8.561520  4.924429 -0.318245

=== WatchAccelerometer.csv ===

                  time  seconds_elapsed         z          y         x
0  1774789947552964400        -0.983036 -0.335188  -0.143652  0.256180
1  1774789947563004700        -0.972995  8.635885  12.428301 -3.275268
2  1774789947582646300        -0.953354 -0.452504  -0.035913  0.428562

=== WatchBarometer.csv ===

                  time  seconds_elapsed     pressure  relativeAltitude
0  1774789947632547800        -0.903452  1023.001953          0.000000
1  1774789947733164300        -0.802836  1023.022705         -0.169106
2  1774789947833780700        -0.702219  1023.022461         -0.169106

=== WatchGravity.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789947572875500        -0.963125  9.123656  2.825015 -2.224539
1  1774789947582646300        -0.953354  9.108047  2.846044 -2.261390
2  1774789947592456200        -0.943544  9.076241  2.902367 -2.317005

=== WatchGyroscope.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789947563004700        -0.972995  0.129503  0.362854  0.488692
1  1774789947582646300        -0.953354 -0.266337  0.538783  0.695165
2  1774789947592456200        -0.943544  0.266337 -0.448375 -0.554666

=== WatchLocation.csv ===

,time,seconds_elapsed,longitude,speedAccuracy,speed,bearingAccuracy,latitude,bearing,horizontalAccuracy,verticalAccuracy,altitude
0,1774789948616083700,0.080084,4.874664,1.5,0.000000,45.0,52.319259,0.0,16.790001,2.007456,67.199997
1,1774789953923614500,5.387615,4.874664,1.5,0.058193,0.0,52.319263,0.0,26.521000,2.033221,67.199997
2,1774789954533522400,5.997522,4.874664,1.5,0.057189,0.0,52.319264,0.0,26.607000,2.033221,67.199997

=== WatchMagnetometer.csv ===

                  time  seconds_elapsed          z      y          x
0  1774789947572875500        -0.963125 -23.279999  26.76   3.240000
1  1774789947582646300        -0.953354 -39.419998  16.98  13.559999
2  1774789947592456200        -0.943544 -55.619999   7.62  24.119999

=== WatchOrientation.csv ===

,time,seconds_elapsed,yaw,pitch,qy,qz,roll,qx,qw
0,1774789947552964400,-0.983036,2.340976,1.484126,0.320316,-0.379640,-1.304362,-0.621292,0.606025
1,1774789947582646300,-0.953354,0.093389,-0.281665,0.125096,-0.027149,0.266892,0.145117,0.981098
2,1774789947592456200,-0.943544,-0.109117,-0.289375,0.134562,0.071986,0.257297,0.135856,0.978904

=== WatchTotalAcceleration.csv ===

                  time  seconds_elapsed         z         y         x
0  1774789947563004700        -0.972995  8.686164  2.501941 -2.492364
1  1774789947582646300        -0.953354  8.595184  3.014300 -1.781286
2  1774789947592456200        -0.943544  8.547300  3.373430 -1.592144

=== WiFi.csv ===

,time,seconds_elapsed,level,frequency,capabilities,BSSID,SSID
0,1774789948535000000,-0.001,-85,5745,[WPA2-PSK-CCMP-128][RSN-PSK-CCMP-128][ESS][WPS],e8:de:27:b1:bf:6a,TP-LINK_BF6B_5G
1,1774789948535000000,-0.001,-63,2447,[WPA2-PSK-CCMP-128][RSN-PSK-CCMP-128][ESS],5c:e9:31:ac:2d:8e,TP-Link_2D8E
2,1774789948535000000,-0.001,-85,5180,[WPA2-PSK-CCMP-128][RSN-PSK-CCMP-128][ESS][WPS],50:91:e3:f9:41:a4,boordeel #2 (snel)

In [4]:
folder_a = Path("./Uilenstede")
folder_b = Path("./Uilenstede-zoo")

# # Get CSV filenames in each folder
# files_a = {f.name for f in folder_a.glob("*.csv")}
# files_b = {f.name for f in folder_b.glob("*.csv")}

# # Intersection = files present in both folders
# common_files = sorted(files_a & files_b)

# print("Common CSV files:", common_files)

common_files = ['Accelerometer.csv', 'Compass.csv', 'Gravity.csv', 'Orientation.csv', 'Pedometer.csv']


for filename in common_files:
    print(f"\n=== {filename} ===")

    file_a = folder_a / filename
    file_b = folder_b / filename

    try:
        df_a = pd.read_csv(file_a)
        df_b = pd.read_csv(file_b)

        print("\n--- Default version (first 3 rows) ---")
        display(df_a.head(3))

        print("\n--- Sensor Zoo version (first 3 rows) ---")
        display(df_b.head(3))

    except Exception as e:
        print(f"Error reading {filename}: {e}")

=== Accelerometer.csv ===

--- Default version (first 3 rows) ---

                  time  seconds_elapsed         z         y         x
0  1774789948640308700         0.104309  0.000000  0.000000  0.000000
1  1774789948677358300         0.141358  0.432748 -0.056351 -0.057238
2  1774789948695883300         0.159883  1.092300 -0.207151  0.070466

--- Sensor Zoo version (first 3 rows) ---

                  time  seconds_elapsed         x         y         z
0  1774790030288921900         0.169922 -0.014379  0.007533 -9.806987
1  1774790030316709600         0.197710 -0.023659  0.028120 -9.806931
2  1774790030335234800         0.216235 -0.028217  0.059170 -9.806781

=== Compass.csv ===

--- Default version (first 3 rows) ---

                  time  seconds_elapsed  magneticBearing
0  1774789948667543600         0.131543       258.098922
1  1774789948677543700         0.141544       253.353411
2  1774789948697543700         0.161544       247.000030

--- Sensor Zoo version (first 3 rows) ---

                  time  seconds_elapsed  magneticBearing
0  1774790030273079600         0.154080       315.937253
1  1774790030293079600         0.174080       316.784605
2  1774790030323079400         0.204079       317.215087

=== Gravity.csv ===

--- Default version (first 3 rows) ---

                  time  seconds_elapsed         z         y         x
0  1774789948640308700         0.104309  8.026459  5.628912 -0.248372
1  1774789948677358300         0.141358  8.079538  5.556170 -0.142901
2  1774789948695883300         0.159883  8.248864  5.303455 -0.001130

--- Sensor Zoo version (first 3 rows) ---

                  time  seconds_elapsed         x         y         z
0  1774790030288921900         0.169922  0.014379 -0.007533  9.806987
1  1774790030316709600         0.197710  0.023659 -0.028120  9.806931
2  1774790030335234800         0.216235  0.028217 -0.059170  9.806781

=== Orientation.csv ===

--- Default version (first 3 rows) ---

,time,seconds_elapsed,qz,qy,qx,qw,roll,pitch,yaw
0,1774789948668096000,0.132096,0.298179,0.104876,0.282123,0.905813,0.026555,-0.610948,-0.627649
1,1774789948695883300,0.159883,0.269332,0.079169,0.270476,0.920888,0.000137,-0.571390,-0.569028
2,1774789948714408000,0.178408,0.264863,0.071825,0.263085,0.924919,-0.007634,-0.552377,-0.559963

--- Sensor Zoo version (first 3 rows) ---

,time,seconds_elapsed,qw,qx,qy,qz,roll,pitch,yaw
0,1774790030270396700,0.151397,0.999998,-0.000385,-0.000733,-0.001616,-0.001466,0.000768,0.003232
1,1774790030288921900,0.169922,0.999998,-0.000385,-0.000733,-0.001616,-0.001466,0.000768,0.003232
2,1774790030316709600,0.197710,0.999988,-0.003022,-0.001428,-0.003534,-0.002877,0.006033,0.007059

=== Pedometer.csv ===

--- Default version (first 3 rows) ---

                  time  seconds_elapsed  steps
0  1774789945843022600        -2.692977      0
1  1774789957374372900         8.838373      6
2  1774789957967303700         9.431304      7

--- Sensor Zoo version (first 3 rows) ---

                  time  seconds_elapsed  steps
0  1774790018923753700       -11.195246      0
1  1774790037902463200         7.783463      5
2  1774790038550913800         8.431914      7